services:
  caddy-build:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - '8443:443'
    volumes:
      - ./docker/Caddyfile.build.mkcert:/etc/caddy/Caddyfile:ro
      - ./.certs:/certs:ro
      - caddy_build_data:/data
      - caddy_build_config:/config
    depends_on:
      - web
      - server

volumes:
  caddy_build_data:
  caddy_build_config:
